export const COPY = {
  app: {
    title: "AI Insurance Assistant",
    subtitle: "Draft compliant follow-ups and call scripts for life insurance clients.",
  },
  tabs: {
    customer: "Customer",
    settings: "Settings",
  },
  buttons: {
    email: "Write the email",
    text: "Write the text",
    script: "Write my call script",
    copy: "Copy",
    copied: "Copied",
    regen: "Try again",
    addPolicy: "Add a policy",
    savePolicy: "Save policy",
    cancelPolicy: "Cancel",
    editPolicy: "Edit",
    deletePolicy: "Delete",
    confirmDelete: "Confirm delete",
    cancelDelete: "Cancel",
    sample: "Load a sample customer",
    extract: "Fill customer details",
    saveProfile: "Save profile",
    savedProfile: "Saved",
    warmer: "Warmer",
    professional: "Professional",
    direct: "Direct",
  },
  sections: {
    quickNotes: "Quick notes",
    quickNotesHelper: "Paste raw notes from your phone call to fill the table automatically.",
    customerDetails: "Customer details",
    outputHeader: "Generated communication",
    agentProfile: "Agent signature profile",
    agentProfileHelper: "These details populate your email signatures and phone intros.",
    policyLibrary: "Policy library",
    policyLibraryHelper: "Carrier cards with exact limitations and key selling points.",
    newPolicyHeader: "New policy",
    editPolicyHeader: "Edit policy",
  },
  fields: {
    name: "Name",
    age: "Age",
    income: "Income",
    policy: "Policy",
    coverageAmount: "Coverage amount",
    termLength: "Term length",
    monthlyPayment: "Monthly payment",
    smoker: "Smoker",
    protecting: "Protecting",
    currentCoverage: "Current coverage",
    stage: "Stage",
    textConsent: "Consent to receive text messages",
    notes: "Notes from conversation",
    quickNotesInput: "Paste raw call notes here",
    agentName: "Full name",
    agentAgency: "Agency or firm",
    agentPhone: "Direct phone",
    agentEmail: "Email address",
    agentStates: "Licensed states",
    policyName: "Policy name",
    policyCarrier: "Carrier",
    policyType: "Type",
    policyAgeMin: "Minimum age",
    policyAgeMax: "Maximum age",
    policyCoverageMin: "Minimum coverage",
    policyCoverageMax: "Maximum coverage",
    policySellingPoints: "Key selling points",
    policyLimitations: "Limitations",
  },
  placeholders: {
    name: "Maria Gonzalez",
    age: "58",
    income: "$42,000/year",
    coverageAmount: "$15,000",
    monthlyPayment: "$67",
    protecting: "Her daughter",
    currentCoverage: "Just through work",
    notes: "Sister passed last year, no money for the service",
    quickNotes: "Spoke with Maria Gonzalez, 58 years old, non smoker. Quoted 15k with Mutual of Omaha for 67 a month to protect her daughter.",
    notSureYet: "Not sure yet",
    agentName: "David Miller",
    agentAgency: "Apex Pinnacle Financial",
    agentPhone: "(555) 234-8901",
    agentEmail: "david.miller@apexpinnacle.com",
    agentStates: "TX, FL, GA, NC, OH",
    policyName: "Living Promise",
    policyCarrier: "Mutual of Omaha",
    policyCoverageMin: "$2,000",
    policyCoverageMax: "$40,000",
    policySellingPoints: "Locked rates for life. Never increases. No medical exams.",
    policyLimitations: "Does not build early cash value. Max coverage 40k.",
  },
  options: {
    yes: "Yes",
    no: "No",
    select: "Select",
    yearsUnit: "yrs",
    term: "Term Life",
    wholeLife: "Whole Life",
    iul: "Indexed Universal Life (IUL)",
    finalExpense: "Final Expense",
  },
  helpers: {
    termLengthDisabled: "Not applicable for permanent life policies.",
    textConsentNeeded: "Consent confirmed by client.",
    tone: "Tone preference",
    deleteWarning: "Are you sure you want to delete this policy?",
    keepOnePolicy: "You need at least one active policy in your library.",
  },
  outputs: {
    subjectLabel: "Subject line",
    bodyLabel: "Email body",
    textLabel: "Text message",
    charactersLabel: "characters",
    characterCounterLabel: "Live character count",
    singleSegmentLabel: "Single segment (under 160)",
    twoSegmentLabel: "Two segments (under 320)",
    overLimitLabel: "Exceeds standard 320 character limit",
    standardLimit: "Standard limit: 320 characters",
    openerLabel: "Opener",
    questionsLabel: "Discovery questions",
    framingLabel: "Value framing",
    objectionsLabel: "Objection handling",
    closeLabel: "Close",
    prospectSays: "Prospect says",
    sayThis: "Say this",
    complianceNote: "Draft for agent review. Verify carrier rates and state disclosures before transmitting.",
  },
  errors: {
    network: "Could not reach the AI. Check your connection and try again.",
    parse: "That came back garbled. Try again and it should sort itself out.",
    consent: "Check the consent box above so you are covered before texting.",
    quickNotesEmpty: "Enter notes first before extracting.",
  },
};
